### ISSUE TITLE
Update lifecycle rules in Terraform

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/terraform_scihist_digicoll#4]
Three buckets -- `aws_s3_bucket.derivatives`, `aws_s3_bucket.dzi`, and `aws_s3_bucket.originals` had their lifecycle rules changed. The new rules need to be described in Terraform.
e.g. for `aws_s3_bucket.originals` we have:
```
          - transition {
              - days          = 0 -> null
              - storage_class = "INTELLIGENT_TIERING" -> null
            }
          + transition {
              + days          = 30
              + storage_class = "STANDARD_IA"
            }
```
This should be trivial once #3  is taken care of.

**Comment by jrochkind** [comment]
I'm comparing changes/terraform state/UI in AWS Console to Chuck's spreadsheet to make sure everything seems to match, as we were surprised that terraform only wants to change _two_ bucket lifecycle rules, we thought there were more manual changes made...

**Comment by jrochkind** [comment]
@CHF-IT-Staff, questions about some inconsistencies/discrepencies I'm noticing:

* Some of the Lifecycle Rule names seem to follow a standard pattern, but some end in `-IT-Rule`, and others in `-IA-Rule`. is this intentional or is `IT` a typo?  And then others are just plain language like "Transition to IA".  Should we leave these inconsistencies or normalize them?

**Comment by jrochkind** [comment]
@CHF-IT-Staff If I understand right, in some cases you want DIFFERENT lifecycle rules for the staging vs production version of the same bucket. 

While this is probably (I think) possible, it definitely makes things a lot harder to describe and maintain in terraform, since our system is based on basically using staging as a testing ground for production and applying exactly what was tested in staging to production. 

I wonder if we could use the same lifecycle rules for both, without giving up too much savings?

**Comment by CHF-IT-Staff** [comment]
We can review the cost per bucket to see.


__________________________________

Chuck Hornstein   (he, him, his)
Director, Information Technology
t. +1.215.873.8272
f. +1.215.629.5272

Science History Institute
Chemistry * Engineering * Life Sciences
315 Chestnut Street * Philadelphia, PA 19106 * U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

**Comment by jrochkind** [comment]
OK, so I can't proceed with this ticket until we make a decision there. Should I try to figure out how to review cost per bucket to see, or is that something you will do? Thanks!

**Comment by CHF-IT-Staff** [comment]
I'll do it


__________________________________

Chuck Hornstein   (he, him, his)
Director, Information Technology
t. +1.215.873.8272
f. +1.215.629.5272

Science History Institute
Chemistry * Engineering * Life Sciences
315 Chestnut Street * Philadelphia, PA 19106 * U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

**Comment by jrochkind** [comment]
@CHF-IT-Staff  confirmed in a meeting that it's okay to have the storage class and lifecycle rules match production and staging. We'll take the desired rules for production, and apply them to staging too.

**Comment by eddierubeiz** [comment]
Still need to actually apply the changes to S3. I will do this BEFORE we close this ticket.
